### ISSUE TITLE
A some new feature - user settings

### ISSUE THREAD

**Issue by stojankukrika** [merodiro/settings#3]
Hi,
I like your project, but if you can make to work like that every user or organization have settings like this it will be very awesome and you will have totally unique product in packages word. Can you add it or build it?

**Comment by merodiro** [comment]
I think something like that needs its own package, I'm not sure how to add this feature without breaking the way it works now, any suggestion?

**Comment by malekbenelouafi** [comment]
Hi what about adding user_id in settings migration nullable (relation one to many), and create a Trait for model to get his settings, for setting without user_id will be assigned as global settings.

**Comment by merodiro** [comment]
I am working on it on dev branch.
I still need to update Readme and make sure that everything works fine.

**Comment by merodiro** [comment]
I updated the readme, I'm not sure yet if the method names are good or no and if I can improve caching

**Comment by stojankukrika** [comment]
It's look ok to me..
